[api1]
api1 ansible_host=API1_PRIVATE_IP ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/deploy_key

[gateway]
gateway ansible_host=GATEWAY_PRIVATE_IP ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/deploy_key

[ci]
ci ansible_host=CI_PUBLIC_IP ansible_user=ec2-user ansible_ssh_private_key_file=/home/ec2-user/.ssh/deploy_key

[eks:children]
ci

[eks:vars]
kubeconfig_path=/home/ec2-user/.kube/config
kubernetes_manifests_dir=/opt/youremail/kubernetes


[all:vars]
ecr_registry=ECR_REGISTRY
ecr_image_api1=ECR_IMAGE_API1
ecr_image_api2=ECR_IMAGE_API2
image_tag=latest
api1_port=5000
frontend_port=80
gateway_config_dest=/etc/nginx/conf.d/youremail.conf
rds_endpoint=RDS_ENDPOINT
rds_port=5432
rds_db_name=youremail
rds_username=youremail
rds_password=
gemini_api_key=
cors_allowed_origins=http://GATEWAY_PUBLIC_IP
rds_read_endpoint=RDS_READ_ENDPOINT
gateway_private_ip=GATEWAY_PRIVATE_IP
public_subnet_ids=PUBLIC_SUBNET_IDS
eks_cluster_name=youremail-homolog
aws_region=us-east-1
aws_account_id=253440504787
