ecr_registry: "{{ lookup('env', 'ECR_REGISTRY') | default('', true) }}"
ecr_password: "{{ lookup('env', 'ECR_PASSWORD') | default('', true) }}"
ecr_image_api1: "{{ lookup('env', 'ECR_IMAGE_API1') | default('', true) }}"
ecr_image_api2: "{{ lookup('env', 'ECR_IMAGE_API2') | default('', true) }}"
image_tag: "{{ lookup('env', 'IMAGE_TAG') | default('latest', true) }}"
aws_region: "{{ lookup('env', 'AWS_REGION') | default('us-east-1', true) }}"
aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') | default('253440504787', true) }}"
eks_cluster_name: "{{ lookup('env', 'EKS_CLUSTER_NAME') | default('youremail-homolog', true) }}"
database_url: "postgresql://{{ rds_username }}:{{ rds_password }}@{{ rds_endpoint }}:{{ rds_port }}/{{ rds_db_name }}"
